services:
  api:
    container_name: ab-resto-api
    restart: always
    build:
      .
    ports:
      - 3000:3000
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    container_name: ab-resto-postgre
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: ab-resto-db
