services:
  api:
    container_name: log-burane-api
    restart: always
    build:
      .
    environment:
      DATABASE_URL : ${DATABASE_URL_DOCKER}
    ports:
      - ${APP_PORT}:${APP_PORT}
    links:
      - postgres
    depends_on:
      - postgres
    .env_file:
      - .env

  postgres:
    container_name: log-burane-postgre
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: log-burane-db
